mysql:
  host: mysql
  port: 3306
  user: reco_user
  password: reco_user
  database: reco_films

csv:
  base_path: /app/data/raw/ml-20m

mlflow:
  tracking_uri: "http://mlflow:8080"

airflow:
  user: admin
  password: FVprYTE2adMNEvXa