{
 "title": "API Performance",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Requests by endpoint",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint) (api_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average API Latency per endpoint",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint) (api_request_duration_seconds_sum / api_request_duration_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nb of request errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_requests_total{status_code!=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total API Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(api_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Error Rate (last 10 min)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_requests_total{status_code!=\"200\"}[10m])) / sum(rate(api_requests_total[10m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}