{
 "title": "Drift Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Rating Drift Detected",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently_rating_drift_detected_status",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dataset drift detected",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently_dataset_drift_detected_status",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rating drift score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "evidently_rating_drift_score", "legendFormat": "__auto" }
   ]
  }
 ]
}